title: Bygdeå
description: Bygdeå en by fyra mil norr om Umeå
email: byalagetskinnarbyn@gmail.com
author:
  name: Byalaget
  email: byalagetskinnarbyn@gmail.com

future: true
show_drafts: false

permalink: /:categories/:title
baseurl: "http://www.bygdea.se"
url: ""

# Markdown library
markdown: rdiscount
#   extensions: []

