title: Bygdeå
description: Bygdeå en by fyra mil norr om Umeå
email: byalagetskinnarbyn@gmail.com
author:
  name: Byalaget
  email: byalagetskinnarbyn@gmail.com

future: true
show_drafts: false

permalink: /:categories/:title
baseurl: "http://www.bygdea.se"
url: ""

# Markdown library
markdown: rdiscount
#   extensions: []

prose:
  rooturl: '_posts'
  siteurl: 'http://www.bygdea.se/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "evenmang"
      - name: "category"
        field:
          element: "hidden"
          value: "evenemang"
      - name: "title"
        field:
          element: "text"
          label: "Titel på evenemang"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Datum och tid"
          value: ""
      - name: "duration"
        field:
          element: "number"
          label: "Minuter"
          value: ""
      - name: "allday"
        field:
          element: "checkbox"
          label: "Heldagsevenemang"
          value: "false"
      - name: "place"
        field:
          element: "text"
          label: "Plats för evenemang"
          value: ""
      - name: "adress"
        field:
          element: "text"
          label: "Adress till platsen"
          value: ""
      - name: "href"
        field:
          element: "text"
          label: "Länk"
          value: ""
